# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace

spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5433/etutor
    username: etutor_admin
    password: secret
  jpa:
    show-sql: true

  # Mail
  mail:
    sender: etutor@dke.uni-linz.ac.at
    host: localhost
    port: 1025
    username:
    password:

# JWT
jwt:
  token-lifetime: 1800
  refresh-token-lifetime: 2000

# Moodle
moodle:
  token: 7c64718cf68f89ea066cf86e1b2a22d3
  url: http://localhost:8000/
