# Logging
logging:
  level:
    ROOT: info
    at.jku.dke: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5433/etutor
    username: etutor_admin
    password: secret
  jpa:
    show-sql: true

  # Mail
  mail:
    sender: etutor@dke.uni-linz.ac.at
    host: localhost
    port: 1025
    username:
    password:

# JWT
jwt:
  token-lifetime: 1800
  refresh-token-lifetime: 2000

# Moodle
moodle:
  enabled: true
  token: bbec36ffa4c4d926b8fd47e5720a4afe
  url: http://localhost:8000/

# Cors Configuration
cors:
  allowed-origins: http://localhost:4200 # comma-separated list of allowed origins
